import { Template, ThemeConfig } from './types';

const base = (t: Partial<ThemeConfig>): ThemeConfig => ({
  primaryColor: '#2563eb',
  secondaryColor: '#3b82f6',
  accentColor: '#f59e0b',
  backgroundColor: '#0a1628',
  textColor: '#f1f5f9',
  fontFamily: 'Inter',
  fontSize: 'md',
  borderRadius: 'md',
  spacing: 'normal',
  animation: 'moderate',
  ...t,
});

/** New 2025 template collection — distinct palettes + layout presets */
export const V2_TEMPLATES: Template[] = [
  {
    id: 'site99-pro',
    name: 'site99 Pro',
    category: 'agency',
    purposes: ['agency-studio', 'saas-startup', 'business-company', 'freelancer-services'],
    thumbnail: '/templates/site99-pro.jpg',
    description: 'Official site99 brand — navy & orange, polished agency feel',
    defaultSections: ['hero', 'about', 'services', 'stats', 'projects', 'testimonials', 'contact'],
    defaultTheme: base({
      primaryColor: '#1a3a5c',
      secondaryColor: '#2d5a7b',
      accentColor: '#f28c28',
      backgroundColor: '#0a1d37',
      textColor: '#f1f5f9',
      fontFamily: 'Inter',
      borderRadius: 'lg',
      animation: 'moderate',
      customCSS: 'nav.navbar { backdrop-filter: blur(16px); border-bottom: 1px solid rgba(247,148,29,0.15); } .hero-inner { gap: 3rem; } a.btn-primary, .cta-btn { background: linear-gradient(135deg, #f7941d, #ffb347); }',
    }),
    defaultLayoutPreset: 'saas-modern',
    layoutTags: ['site99', 'Agency'],
    previewVariant: 'split',
  },
  {
    id: 'aurora-saas',
    name: 'Aurora SaaS',
    category: 'saas',
    purposes: ['saas-startup', 'business-company', 'online-store'],
    thumbnail: '/templates/aurora-saas.jpg',
    description: 'Gradient glow SaaS landing with pricing and social proof',
    defaultSections: ['hero', 'about', 'services', 'stats', 'pricing', 'faq', 'testimonials', 'contact'],
    defaultTheme: base({
      primaryColor: '#8b5cf6',
      secondaryColor: '#06b6d4',
      accentColor: '#f472b6',
      backgroundColor: '#030712',
      textColor: '#f9fafb',
      fontFamily: 'Space Grotesk',
      borderRadius: 'lg',
      animation: 'expressive',
      customCSS: 'section[id] { position: relative; } .hero-inner::before { content:""; position:absolute; inset:-20%; background: radial-gradient(circle at 30% 20%, rgba(139,92,246,0.25), transparent 55%); pointer-events:none; }',
    }),
    defaultLayoutPreset: 'one-page',
    layoutTags: ['Gradient', 'SaaS'],
    previewVariant: 'banner',
  },
  {
    id: 'noir-creative',
    name: 'Noir Creative',
    category: 'designer',
    purposes: ['personal-portfolio', 'agency-studio', 'photography-studio'],
    thumbnail: '/templates/noir-creative.jpg',
    description: 'High-contrast dark studio with bold typography',
    defaultSections: ['hero', 'about', 'projects', 'gallery', 'testimonials', 'contact'],
    defaultTheme: base({
      primaryColor: '#fafafa',
      secondaryColor: '#a3a3a3',
      accentColor: '#ef4444',
      backgroundColor: '#0a0a0a',
      textColor: '#fafafa',
      fontFamily: 'Montserrat',
      borderRadius: 'none',
      animation: 'expressive',
      spacing: 'relaxed',
    }),
    defaultLayoutPreset: 'asymmetrical',
    layoutTags: ['Dark', 'Portfolio'],
    previewVariant: 'split',
  },
  {
    id: 'golden-luxe',
    name: 'Golden Luxe',
    category: 'realestate',
    purposes: ['real-estate', 'law-consulting', 'event-wedding', 'online-store'],
    thumbnail: '/templates/golden-luxe.jpg',
    description: 'Premium gold accents for luxury brands and estates',
    defaultSections: ['hero', 'about', 'gallery', 'services', 'stats', 'testimonials', 'contact'],
    defaultTheme: base({
      primaryColor: '#d4af37',
      secondaryColor: '#b8960c',
      accentColor: '#fef3c7',
      backgroundColor: '#0c0a09',
      textColor: '#fafaf9',
      fontFamily: 'Cormorant Garamond',
      borderRadius: 'none',
      animation: 'subtle',
    }),
    defaultLayoutPreset: 'featured-hero',
    layoutTags: ['Luxury', 'Premium'],
    previewVariant: 'banner',
  },
  {
    id: 'mint-wellness',
    name: 'Mint Wellness',
    category: 'healthcare',
    purposes: ['healthcare-clinic', 'fitness-coach', 'education-course'],
    thumbnail: '/templates/mint-wellness.jpg',
    description: 'Fresh calming palette for health, wellness, and coaching',
    defaultSections: ['hero', 'about', 'services', 'team', 'testimonials', 'faq', 'contact'],
    defaultTheme: base({
      primaryColor: '#0d9488',
      secondaryColor: '#5eead4',
      accentColor: '#14b8a6',
      backgroundColor: '#f0fdfa',
      textColor: '#134e4a',
      fontFamily: 'DM Sans',
      borderRadius: 'lg',
      animation: 'subtle',
    }),
    defaultLayoutPreset: 'split-screen',
    layoutTags: ['Wellness', 'Light'],
    previewVariant: 'center',
  },
  {
    id: 'sunset-studio',
    name: 'Sunset Studio',
    category: 'creative',
    purposes: ['personal-portfolio', 'photography-studio', 'music-artist', 'blog-writer'],
    thumbnail: '/templates/sunset-studio.jpg',
    description: 'Warm sunset gradients for artists and visual storytellers',
    defaultSections: ['hero', 'about', 'gallery', 'projects', 'contact'],
    defaultTheme: base({
      primaryColor: '#ea580c',
      secondaryColor: '#fb923c',
      accentColor: '#fbbf24',
      backgroundColor: '#1c1917',
      textColor: '#fef3c7',
      fontFamily: 'Raleway',
      borderRadius: 'md',
      animation: 'moderate',
      customCSS: '.hero-inner { background: linear-gradient(135deg, rgba(234,88,12,0.15), rgba(251,146,60,0.08)); border-radius: 1rem; padding: 2rem; }',
    }),
    defaultLayoutPreset: 'featured-hero',
    layoutTags: ['Warm', 'Creative'],
    previewVariant: 'banner',
  },
  {
    id: 'graphite-minimal',
    name: 'Graphite Minimal',
    category: 'minimal',
    purposes: ['resume-cv', 'freelancer-services', 'blog-writer', 'business-company'],
    thumbnail: '/templates/graphite-minimal.jpg',
    description: 'Swiss-style minimal with sharp typography and whitespace',
    defaultSections: ['hero', 'about', 'experience', 'projects', 'contact'],
    defaultTheme: base({
      primaryColor: '#18181b',
      secondaryColor: '#52525b',
      accentColor: '#2563eb',
      backgroundColor: '#ffffff',
      textColor: '#18181b',
      fontFamily: 'Inter',
      borderRadius: 'none',
      animation: 'none',
      spacing: 'compact',
    }),
    defaultLayoutPreset: 'single-column',
    layoutTags: ['Minimal', 'Clean'],
    previewVariant: 'center',
  },
  {
    id: 'neon-dev',
    name: 'Neon Dev',
    category: 'developer',
    purposes: ['personal-portfolio', 'saas-startup', 'freelancer-services'],
    thumbnail: '/templates/neon-dev.jpg',
    description: 'Cyberpunk terminal aesthetic for developers and hackers',
    defaultSections: ['hero', 'skills', 'projects', 'experience', 'contact'],
    defaultTheme: base({
      primaryColor: '#22d3ee',
      secondaryColor: '#a855f7',
      accentColor: '#4ade80',
      backgroundColor: '#020617',
      textColor: '#e2e8f0',
      fontFamily: 'JetBrains Mono',
      borderRadius: 'sm',
      animation: 'expressive',
      customCSS: 'nav.navbar { border-bottom: 1px solid rgba(34,211,238,0.2); } .section-title { text-shadow: 0 0 24px rgba(34,211,238,0.35); }',
    }),
    defaultLayoutPreset: 'grid-cards',
    layoutTags: ['Neon', 'Developer'],
    previewVariant: 'cards',
  },
  {
    id: 'rose-boutique',
    name: 'Rose Boutique',
    category: 'ecommerce',
    purposes: ['online-store', 'event-wedding', 'photography-studio'],
    thumbnail: '/templates/rose-boutique.jpg',
    description: 'Soft rose palette for fashion, beauty, and lifestyle brands',
    defaultSections: ['hero', 'about', 'gallery', 'pricing', 'testimonials', 'faq', 'contact'],
    defaultTheme: base({
      primaryColor: '#db2777',
      secondaryColor: '#f9a8d4',
      accentColor: '#831843',
      backgroundColor: '#fff1f2',
      textColor: '#500724',
      fontFamily: 'Playfair Display',
      borderRadius: 'full',
      animation: 'subtle',
    }),
    defaultLayoutPreset: 'shop-showcase',
    layoutTags: ['Fashion', 'Shop'],
    previewVariant: 'cards',
  },
  {
    id: 'navy-corporate',
    name: 'Navy Corporate',
    category: 'business',
    purposes: ['business-company', 'law-consulting', 'agency-studio', 'construction-trades'],
    thumbnail: '/templates/navy-corporate.jpg',
    description: 'Trust-building corporate with stats, team, and case studies',
    defaultSections: ['hero', 'about', 'services', 'stats', 'team', 'testimonials', 'contact'],
    defaultTheme: base({
      primaryColor: '#1e40af',
      secondaryColor: '#3b82f6',
      accentColor: '#0ea5e9',
      backgroundColor: '#f8fafc',
      textColor: '#0f172a',
      fontFamily: 'Source Sans 3',
      borderRadius: 'md',
      animation: 'subtle',
    }),
    defaultLayoutPreset: 'f-shape',
    layoutTags: ['Corporate', 'B2B'],
    previewVariant: 'split',
  },
  {
    id: 'forest-impact',
    name: 'Forest Impact',
    category: 'nonprofit',
    purposes: ['nonprofit-charity', 'education-course', 'travel-hospitality'],
    thumbnail: '/templates/forest-impact.jpg',
    description: 'Earthy greens for nonprofits, eco brands, and missions',
    defaultSections: ['hero', 'about', 'stats', 'services', 'team', 'testimonials', 'contact'],
    defaultTheme: base({
      primaryColor: '#15803d',
      secondaryColor: '#4ade80',
      accentColor: '#fef08a',
      backgroundColor: '#052e16',
      textColor: '#ecfdf5',
      fontFamily: 'Nunito',
      borderRadius: 'lg',
      animation: 'moderate',
    }),
    defaultLayoutPreset: 'holy-grail',
    layoutTags: ['Eco', 'Nonprofit'],
    previewVariant: 'center',
  },
  {
    id: 'violet-startup',
    name: 'Violet Startup',
    category: 'landing',
    purposes: ['saas-startup', 'online-store', 'agency-studio', 'fitness-coach'],
    thumbnail: '/templates/violet-startup.jpg',
    description: 'Bold startup landing with Z-flow sections and pricing',
    defaultSections: ['hero', 'about', 'services', 'stats', 'pricing', 'testimonials', 'faq', 'contact'],
    defaultTheme: base({
      primaryColor: '#7c3aed',
      secondaryColor: '#c084fc',
      accentColor: '#fbbf24',
      backgroundColor: '#0f0a1e',
      textColor: '#faf5ff',
      fontFamily: 'Poppins',
      borderRadius: 'lg',
      animation: 'expressive',
    }),
    defaultLayoutPreset: 'z-shape',
    layoutTags: ['Startup', 'Landing'],
    previewVariant: 'cards',
  },
  {
    id: 'editorial-mag',
    name: 'Editorial Mag',
    category: 'blog',
    purposes: ['blog-writer', 'travel-hospitality', 'personal-portfolio'],
    thumbnail: '/templates/editorial-mag.jpg',
    description: 'Magazine-style editorial with blog-forward content hub',
    defaultSections: ['hero', 'about', 'blog', 'gallery', 'social', 'contact'],
    defaultTheme: base({
      primaryColor: '#44403c',
      secondaryColor: '#78716c',
      accentColor: '#dc2626',
      backgroundColor: '#fafaf9',
      textColor: '#1c1917',
      fontFamily: 'Lora',
      borderRadius: 'none',
      animation: 'subtle',
      spacing: 'relaxed',
    }),
    defaultLayoutPreset: 'magazine',
    layoutTags: ['Magazine', 'Blog'],
    previewVariant: 'magazine',
  },
  {
    id: 'bistro-warm',
    name: 'Bistro Warm',
    category: 'restaurant',
    purposes: ['restaurant-food', 'event-wedding', 'travel-hospitality'],
    thumbnail: '/templates/bistro-warm.jpg',
    description: 'Cozy bistro feel with gallery, menu services, and reservations',
    defaultSections: ['hero', 'about', 'gallery', 'services', 'testimonials', 'faq', 'contact'],
    defaultTheme: base({
      primaryColor: '#92400e',
      secondaryColor: '#d97706',
      accentColor: '#fde68a',
      backgroundColor: '#292524',
      textColor: '#fef3c7',
      fontFamily: 'Playfair Display',
      borderRadius: 'sm',
      animation: 'subtle',
    }),
    defaultLayoutPreset: 'featured-hero',
    layoutTags: ['Restaurant', 'Warm'],
    previewVariant: 'banner',
  },
  {
    id: 'marketplace-pro',
    name: 'Marketplace Pro',
    category: 'marketplace',
    purposes: ['online-store', 'freelancer-services', 'construction-trades'],
    thumbnail: '/templates/marketplace-pro.jpg',
    description: 'Multi-category marketplace with product grid and vendor stats',
    defaultSections: ['hero', 'about', 'gallery', 'services', 'stats', 'pricing', 'faq', 'contact'],
    defaultTheme: base({
      primaryColor: '#2563eb',
      secondaryColor: '#60a5fa',
      accentColor: '#f97316',
      backgroundColor: '#eff6ff',
      textColor: '#1e3a8a',
      fontFamily: 'Inter',
      borderRadius: 'lg',
      animation: 'moderate',
    }),
    defaultLayoutPreset: 'grid-cards',
    layoutTags: ['Marketplace', 'Grid'],
    previewVariant: 'cards',
  },
];

export function inferPreviewVariant(template: Template): NonNullable<Template['previewVariant']> {
  if (template.previewVariant) return template.previewVariant;
  if (template.category === 'blog') return 'magazine';
  if (['ecommerce', 'marketplace'].includes(template.category)) return 'cards';
  if (['minimal', 'healthcare', 'nonprofit'].includes(template.category)) return 'center';
  if (['photographer', 'restaurant', 'creative', 'landing'].includes(template.category)) return 'banner';
  return 'split';
}
