import { Template, ThemeConfig } from './types';

const base = (t: Partial<ThemeConfig>): ThemeConfig => ({
  primaryColor: '#6366f1',
  secondaryColor: '#8b5cf6',
  accentColor: '#f59e0b',
  backgroundColor: '#0f0f0f',
  textColor: '#f1f5f9',
  fontFamily: 'Inter',
  fontSize: 'md',
  borderRadius: 'md',
  spacing: 'normal',
  animation: 'moderate',
  ...t,
});

export const EXTRA_TEMPLATES: Template[] = [
  {
    id: 'business-executive',
    name: 'Business Executive',
    category: 'business',
    purposes: ['business-company', 'law-consulting', 'freelancer-services'],
    thumbnail: '/templates/business-executive.jpg',
    description: 'Trust-focused corporate layout for established businesses',
    defaultSections: ['hero', 'about', 'services', 'stats', 'team', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#1e3a5f', secondaryColor: '#2563eb', backgroundColor: '#ffffff', textColor: '#0f172a', fontFamily: 'Inter', animation: 'subtle' }),
  },
  {
    id: 'shop-boutique',
    name: 'Shop Boutique',
    category: 'ecommerce',
    purposes: ['online-store'],
    thumbnail: '/templates/shop-boutique.jpg',
    description: 'Elegant product showcase for fashion and lifestyle brands',
    defaultSections: ['hero', 'about', 'gallery', 'pricing', 'testimonials', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#be185d', secondaryColor: '#f472b6', backgroundColor: '#fffbf7', textColor: '#1c1917', fontFamily: 'Playfair Display', borderRadius: 'sm', animation: 'subtle' }),
    defaultLayoutPreset: 'shop-showcase',
  },
  {
    id: 'shop-modern',
    name: 'Shop Modern',
    category: 'ecommerce',
    purposes: ['online-store'],
    thumbnail: '/templates/shop-modern.jpg',
    description: 'Bold modern storefront for DTC and product brands',
    defaultSections: ['hero', 'gallery', 'services', 'pricing', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#111827', secondaryColor: '#6b7280', accentColor: '#f97316', backgroundColor: '#fafafa', textColor: '#111827', fontFamily: 'DM Sans', borderRadius: 'lg' }),
  },
  {
    id: 'restaurant-elegant',
    name: 'Restaurant Elegant',
    category: 'restaurant',
    purposes: ['restaurant-food', 'travel-hospitality'],
    thumbnail: '/templates/restaurant-elegant.jpg',
    description: 'Warm fine-dining aesthetic with gallery and reservations',
    defaultSections: ['hero', 'about', 'gallery', 'services', 'testimonials', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#92400e', secondaryColor: '#d97706', backgroundColor: '#1c1410', textColor: '#fef3c7', fontFamily: 'Playfair Display', borderRadius: 'sm', animation: 'subtle' }),
  },
  {
    id: 'cafe-fresh',
    name: 'Café Fresh',
    category: 'restaurant',
    purposes: ['restaurant-food'],
    thumbnail: '/templates/cafe-fresh.jpg',
    description: 'Bright friendly layout for cafés and bakeries',
    defaultSections: ['hero', 'about', 'gallery', 'services', 'contact'],
    defaultTheme: base({ primaryColor: '#15803d', secondaryColor: '#86efac', backgroundColor: '#fefce8', textColor: '#14532d', fontFamily: 'Poppins', borderRadius: 'lg', animation: 'moderate' }),
  },
  {
    id: 'realestate-luxury',
    name: 'Real Estate Luxury',
    category: 'realestate',
    purposes: ['real-estate', 'construction-trades'],
    thumbnail: '/templates/realestate-luxury.jpg',
    description: 'Premium property showcase with stats and testimonials',
    defaultSections: ['hero', 'about', 'gallery', 'services', 'stats', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#1e293b', secondaryColor: '#ca8a04', backgroundColor: '#0f172a', textColor: '#f8fafc', fontFamily: 'Cormorant Garamond', borderRadius: 'none', animation: 'subtle' }),
  },
  {
    id: 'saas-landing',
    name: 'SaaS Landing',
    category: 'saas',
    purposes: ['saas-startup', 'business-company'],
    thumbnail: '/templates/saas-landing.jpg',
    description: 'High-converting SaaS landing with pricing and FAQ',
    defaultSections: ['hero', 'about', 'services', 'stats', 'pricing', 'faq', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#4f46e5', secondaryColor: '#06b6d4', backgroundColor: '#030712', textColor: '#f9fafb', fontFamily: 'Inter', borderRadius: 'lg', animation: 'expressive' }),
    defaultLayoutPreset: 'saas-modern',
  },
  {
    id: 'saas-minimal',
    name: 'SaaS Minimal',
    category: 'saas',
    purposes: ['saas-startup'],
    thumbnail: '/templates/saas-minimal.jpg',
    description: 'Clean light SaaS product page',
    defaultSections: ['hero', 'services', 'pricing', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#0f766e', secondaryColor: '#14b8a6', backgroundColor: '#ffffff', textColor: '#134e4a', fontFamily: 'Inter', animation: 'subtle', spacing: 'relaxed' }),
  },
  {
    id: 'wedding-romance',
    name: 'Wedding Romance',
    category: 'event',
    purposes: ['event-wedding', 'photography-studio'],
    thumbnail: '/templates/wedding-romance.jpg',
    description: 'Soft romantic layout for weddings and celebrations',
    defaultSections: ['hero', 'about', 'gallery', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#be123c', secondaryColor: '#fda4af', backgroundColor: '#fff1f2', textColor: '#4c0519', fontFamily: 'Playfair Display', borderRadius: 'full', animation: 'subtle' }),
  },
  {
    id: 'nonprofit-hope',
    name: 'Nonprofit Hope',
    category: 'nonprofit',
    purposes: ['nonprofit-charity'],
    thumbnail: '/templates/nonprofit-hope.jpg',
    description: 'Mission-driven layout with impact stats and team',
    defaultSections: ['hero', 'about', 'stats', 'team', 'testimonials', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#0369a1', secondaryColor: '#38bdf8', backgroundColor: '#f0f9ff', textColor: '#0c4a6e', fontFamily: 'Source Sans 3', animation: 'moderate' }),
  },
  {
    id: 'edu-academy',
    name: 'Edu Academy',
    category: 'education',
    purposes: ['education-course'],
    thumbnail: '/templates/edu-academy.jpg',
    description: 'Course and coaching site with pricing and FAQ',
    defaultSections: ['hero', 'about', 'services', 'pricing', 'faq', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#7c3aed', secondaryColor: '#a78bfa', backgroundColor: '#faf5ff', textColor: '#3b0764', fontFamily: 'Nunito', borderRadius: 'lg' }),
  },
  {
    id: 'medical-care',
    name: 'Medical Care',
    category: 'healthcare',
    purposes: ['healthcare-clinic'],
    thumbnail: '/templates/medical-care.jpg',
    description: 'Calm trustworthy layout for clinics and wellness',
    defaultSections: ['hero', 'about', 'services', 'team', 'faq', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#0284c7', secondaryColor: '#22d3ee', backgroundColor: '#f8fafc', textColor: '#0f172a', fontFamily: 'Inter', borderRadius: 'md', animation: 'subtle' }),
  },
  {
    id: 'fitness-power',
    name: 'Fitness Power',
    category: 'fitness',
    purposes: ['fitness-coach'],
    thumbnail: '/templates/fitness-power.jpg',
    description: 'High-energy coaching site with programs and pricing',
    defaultSections: ['hero', 'about', 'services', 'pricing', 'testimonials', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#dc2626', secondaryColor: '#f97316', backgroundColor: '#09090b', textColor: '#fafafa', fontFamily: 'Oswald', borderRadius: 'sm', animation: 'expressive' }),
  },
  {
    id: 'law-firm-classic',
    name: 'Law Firm Classic',
    category: 'legal',
    purposes: ['law-consulting'],
    thumbnail: '/templates/law-firm.jpg',
    description: 'Authoritative layout for legal and consulting firms',
    defaultSections: ['hero', 'about', 'services', 'team', 'faq', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#1e3a8a', secondaryColor: '#64748b', backgroundColor: '#ffffff', textColor: '#1e293b', fontFamily: 'Merriweather', borderRadius: 'none', animation: 'none' }),
  },
  {
    id: 'travel-explorer',
    name: 'Travel Explorer',
    category: 'travel',
    purposes: ['travel-hospitality'],
    thumbnail: '/templates/travel-explorer.jpg',
    description: 'Immersive travel and hospitality showcase',
    defaultSections: ['hero', 'gallery', 'about', 'services', 'pricing', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#0891b2', secondaryColor: '#fbbf24', backgroundColor: '#042f2e', textColor: '#ecfeff', fontFamily: 'Raleway', borderRadius: 'lg', animation: 'moderate' }),
  },
  {
    id: 'construction-pro',
    name: 'Construction Pro',
    category: 'construction',
    purposes: ['construction-trades', 'real-estate'],
    thumbnail: '/templates/construction-pro.jpg',
    description: 'Rugged professional site for contractors and trades',
    defaultSections: ['hero', 'about', 'services', 'gallery', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#b45309', secondaryColor: '#78716c', backgroundColor: '#1c1917', textColor: '#fafaf9', fontFamily: 'Roboto', borderRadius: 'sm', animation: 'subtle' }),
  },
  {
    id: 'blog-editorial',
    name: 'Blog Editorial',
    category: 'minimal',
    purposes: ['blog-writer', 'personal-portfolio'],
    thumbnail: '/templates/blog-editorial.jpg',
    description: 'Typography-first blog and writer portfolio',
    defaultSections: ['hero', 'about', 'blog', 'social', 'contact'],
    defaultTheme: base({ primaryColor: '#292524', secondaryColor: '#78716c', backgroundColor: '#fafaf9', textColor: '#1c1917', fontFamily: 'Lora', borderRadius: 'none', animation: 'subtle', spacing: 'relaxed' }),
    defaultLayoutPreset: 'magazine',
  },
  {
    id: 'coach-life',
    name: 'Life Coach',
    category: 'fitness',
    purposes: ['fitness-coach', 'freelancer-services', 'education-course'],
    thumbnail: '/templates/coach-life.jpg',
    description: 'Warm empowering layout for coaches and mentors',
    defaultSections: ['hero', 'about', 'services', 'testimonials', 'pricing', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#9333ea', secondaryColor: '#f0abfc', backgroundColor: '#fdf4ff', textColor: '#581c87', fontFamily: 'Nunito', borderRadius: 'full', animation: 'moderate' }),
  },
  {
    id: 'podcast-host',
    name: 'Podcast Host',
    category: 'creative',
    purposes: ['blog-writer', 'music-artist', 'personal-portfolio'],
    thumbnail: '/templates/podcast-host.jpg',
    description: 'Dark immersive layout for podcasters and creators',
    defaultSections: ['hero', 'about', 'videos', 'blog', 'social', 'contact'],
    defaultTheme: base({ primaryColor: '#a855f7', secondaryColor: '#ec4899', backgroundColor: '#0c0a09', textColor: '#fafaf9', fontFamily: 'Space Grotesk', borderRadius: 'lg', animation: 'expressive' }),
  },
  {
    id: 'event-conference',
    name: 'Event Conference',
    category: 'event',
    purposes: ['event-wedding', 'education-course', 'saas-startup'],
    thumbnail: '/templates/event-conference.jpg',
    description: 'Bold event landing with schedule and speakers vibe',
    defaultSections: ['hero', 'about', 'team', 'pricing', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#e11d48', secondaryColor: '#fb7185', backgroundColor: '#18181b', textColor: '#fafafa', fontFamily: 'Poppins', borderRadius: 'md', animation: 'expressive' }),
  },
];
