import { Template, ThemeConfig } from './types';
import { LayoutPresetId } from './purpose-layouts';

const base = (t: Partial<ThemeConfig>): ThemeConfig => ({
  primaryColor: '#6366f1',
  secondaryColor: '#8b5cf6',
  accentColor: '#f59e0b',
  backgroundColor: '#0f0f0f',
  textColor: '#f1f5f9',
  fontFamily: 'Inter',
  fontSize: 'md',
  borderRadius: 'md',
  spacing: 'normal',
  animation: 'moderate',
  ...t,
});

type ProTemplate = Template & { defaultLayoutPreset: LayoutPresetId };

export const PROFESSIONAL_TEMPLATES: ProTemplate[] = [
  // ── Corporate / Business ──
  {
    id: 'corp-executive',
    name: 'Corporate Executive',
    category: 'business',
    purposes: ['business-company', 'law-consulting', 'agency-studio'],
    thumbnail: '/templates/corp-executive.jpg',
    description: 'Premium corporate site with trust signals, team, and stats',
    defaultSections: ['hero', 'about', 'services', 'stats', 'team', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#0f172a', secondaryColor: '#334155', accentColor: '#0ea5e9', backgroundColor: '#ffffff', textColor: '#0f172a', fontFamily: 'Inter', animation: 'subtle', spacing: 'normal' }),
    defaultLayoutPreset: 'f-shape',
    layoutTags: ['F-Shape', 'Corporate'],
  },
  {
    id: 'corp-enterprise',
    name: 'Enterprise Pro',
    category: 'business',
    purposes: ['business-company', 'saas-startup', 'agency-studio'],
    thumbnail: '/templates/corp-enterprise.jpg',
    description: 'Large-scale business layout with holy grail structure and pricing',
    defaultSections: ['hero', 'about', 'services', 'stats', 'team', 'pricing', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#1d4ed8', secondaryColor: '#3b82f6', accentColor: '#fbbf24', backgroundColor: '#f8fafc', textColor: '#0f172a', fontFamily: 'DM Sans', borderRadius: 'md' }),
    defaultLayoutPreset: 'holy-grail',
    layoutTags: ['Holy Grail', 'Corporate'],
  },
  {
    id: 'corp-trust',
    name: 'Trust & Authority',
    category: 'business',
    purposes: ['business-company', 'healthcare-clinic', 'law-consulting'],
    thumbnail: '/templates/corp-trust.jpg',
    description: 'Split-screen professional layout for B2B and service firms',
    defaultSections: ['hero', 'about', 'services', 'stats', 'testimonials', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#065f46', secondaryColor: '#10b981', backgroundColor: '#ffffff', textColor: '#064e3b', fontFamily: 'Source Sans 3', animation: 'subtle' }),
    defaultLayoutPreset: 'split-screen',
    layoutTags: ['Split Screen', 'Corporate'],
  },

  // ── Service Provider ──
  {
    id: 'service-premium',
    name: 'Service Provider Pro',
    category: 'business',
    purposes: ['freelancer-services', 'law-consulting', 'fitness-coach', 'education-course'],
    thumbnail: '/templates/service-premium.jpg',
    description: 'Z-shape flow with pricing, FAQ, and client testimonials',
    defaultSections: ['hero', 'about', 'services', 'pricing', 'testimonials', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#7c3aed', secondaryColor: '#a78bfa', backgroundColor: '#faf5ff', textColor: '#3b0764', fontFamily: 'Poppins', borderRadius: 'lg' }),
    defaultLayoutPreset: 'z-shape',
    layoutTags: ['Z-Shape', 'Services'],
  },
  {
    id: 'service-consulting',
    name: 'Consulting Elite',
    category: 'business',
    purposes: ['freelancer-services', 'law-consulting', 'agency-studio'],
    thumbnail: '/templates/service-consulting.jpg',
    description: 'F-shape scan path optimized for consulting and advisory firms',
    defaultSections: ['hero', 'about', 'services', 'stats', 'team', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#1e3a8a', secondaryColor: '#64748b', backgroundColor: '#ffffff', textColor: '#1e293b', fontFamily: 'Merriweather', borderRadius: 'none', animation: 'none' }),
    defaultLayoutPreset: 'f-shape',
    layoutTags: ['F-Shape', 'Consulting'],
  },

  // ── E-Commerce / Retail ──
  {
    id: 'ecom-luxury',
    name: 'Luxury Retail',
    category: 'ecommerce',
    purposes: ['online-store'],
    thumbnail: '/templates/ecom-luxury.jpg',
    description: 'Featured hero slideshow with premium product gallery grid',
    defaultSections: ['hero', 'about', 'gallery', 'pricing', 'testimonials', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#18181b', secondaryColor: '#a1a1aa', accentColor: '#d4af37', backgroundColor: '#09090b', textColor: '#fafafa', fontFamily: 'Cormorant Garamond', borderRadius: 'none', animation: 'subtle' }),
    defaultLayoutPreset: 'featured-hero',
    layoutTags: ['Featured Hero', 'E-Commerce'],
  },
  {
    id: 'ecom-modern-store',
    name: 'Modern Storefront',
    category: 'ecommerce',
    purposes: ['online-store'],
    thumbnail: '/templates/ecom-modern-store.jpg',
    description: 'Card-based product grid with shop showcase layout',
    defaultSections: ['hero', 'gallery', 'services', 'pricing', 'testimonials', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#ea580c', secondaryColor: '#fb923c', backgroundColor: '#fff7ed', textColor: '#431407', fontFamily: 'DM Sans', borderRadius: 'lg', animation: 'moderate' }),
    defaultLayoutPreset: 'grid-cards',
    layoutTags: ['Grid Cards', 'E-Commerce'],
  },
  {
    id: 'ecom-dtc',
    name: 'DTC Brand',
    category: 'ecommerce',
    purposes: ['online-store', 'saas-startup'],
    thumbnail: '/templates/ecom-dtc.jpg',
    description: 'One-page scroll landing optimized for direct-to-consumer brands',
    defaultSections: ['hero', 'about', 'gallery', 'pricing', 'testimonials', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#db2777', secondaryColor: '#f472b6', backgroundColor: '#fdf2f8', textColor: '#831843', fontFamily: 'Poppins', borderRadius: 'full', animation: 'expressive' }),
    defaultLayoutPreset: 'one-page',
    layoutTags: ['One-Page', 'Retail'],
  },

  // ── Marketplace ──
  {
    id: 'marketplace-hub',
    name: 'Marketplace Hub',
    category: 'marketplace',
    purposes: ['online-store', 'freelancer-services', 'travel-hospitality'],
    thumbnail: '/templates/marketplace-hub.jpg',
    description: 'Multi-vendor marketplace with grid cards and category showcase',
    defaultSections: ['hero', 'about', 'gallery', 'services', 'stats', 'pricing', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#2563eb', secondaryColor: '#60a5fa', accentColor: '#f59e0b', backgroundColor: '#f0f9ff', textColor: '#1e3a8a', fontFamily: 'Inter', borderRadius: 'lg' }),
    defaultLayoutPreset: 'grid-cards',
    layoutTags: ['Grid Cards', 'Marketplace'],
  },
  {
    id: 'marketplace-physical',
    name: 'Physical Goods Marketplace',
    category: 'marketplace',
    purposes: ['online-store', 'construction-trades', 'real-estate'],
    thumbnail: '/templates/marketplace-physical.jpg',
    description: 'Holy grail layout for multi-category physical product listings',
    defaultSections: ['hero', 'about', 'gallery', 'services', 'stats', 'pricing', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#b45309', secondaryColor: '#78716c', backgroundColor: '#fafaf9', textColor: '#292524', fontFamily: 'Roboto', borderRadius: 'md' }),
    defaultLayoutPreset: 'holy-grail',
    layoutTags: ['Holy Grail', 'Marketplace'],
  },
  {
    id: 'marketplace-digital',
    name: 'Digital Products Store',
    category: 'marketplace',
    purposes: ['online-store', 'saas-startup', 'education-course'],
    thumbnail: '/templates/marketplace-digital.jpg',
    description: 'SaaS-style layout for digital downloads, courses, and subscriptions',
    defaultSections: ['hero', 'about', 'services', 'pricing', 'faq', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#0891b2', secondaryColor: '#22d3ee', backgroundColor: '#ecfeff', textColor: '#164e63', fontFamily: 'Inter', borderRadius: 'lg', animation: 'moderate' }),
    defaultLayoutPreset: 'saas-modern',
    layoutTags: ['SaaS Modern', 'Digital Store'],
  },

  // ── Portfolio ──
  {
    id: 'portfolio-showcase',
    name: 'Portfolio Showcase',
    category: 'creative',
    purposes: ['personal-portfolio', 'agency-studio', 'photography-studio'],
    thumbnail: '/templates/portfolio-showcase.jpg',
    description: 'Asymmetrical creative layout for designers and artists',
    defaultSections: ['hero', 'about', 'projects', 'gallery', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#e11d48', secondaryColor: '#fb7185', backgroundColor: '#0c0a09', textColor: '#fafaf9', fontFamily: 'Space Grotesk', borderRadius: 'none', animation: 'expressive' }),
    defaultLayoutPreset: 'asymmetrical',
    layoutTags: ['Asymmetrical', 'Portfolio'],
  },
  {
    id: 'portfolio-grid-pro',
    name: 'Portfolio Grid Pro',
    category: 'designer',
    purposes: ['personal-portfolio', 'photography-studio', 'agency-studio'],
    thumbnail: '/templates/portfolio-grid-pro.jpg',
    description: 'Uniform project card grid with split-screen hero',
    defaultSections: ['hero', 'about', 'projects', 'gallery', 'skills', 'contact'],
    defaultTheme: base({ primaryColor: '#6366f1', secondaryColor: '#818cf8', backgroundColor: '#fafafa', textColor: '#18181b', fontFamily: 'Inter', borderRadius: 'md', animation: 'subtle' }),
    defaultLayoutPreset: 'grid-cards',
    layoutTags: ['Grid Cards', 'Portfolio'],
  },
  {
    id: 'portfolio-split',
    name: 'Portfolio Split',
    category: 'designer',
    purposes: ['personal-portfolio', 'freelancer-services', 'resume-cv'],
    thumbnail: '/templates/portfolio-split.jpg',
    description: '50/50 split hero with side-by-side project presentation',
    defaultSections: ['hero', 'about', 'projects', 'skills', 'experience', 'contact'],
    defaultTheme: base({ primaryColor: '#059669', secondaryColor: '#34d399', backgroundColor: '#f0fdf4', textColor: '#14532d', fontFamily: 'DM Sans', borderRadius: 'lg' }),
    defaultLayoutPreset: 'split-screen',
    layoutTags: ['Split Screen', 'Portfolio'],
  },

  // ── Blog / Magazine ──
  {
    id: 'magazine-editorial',
    name: 'Magazine Editorial',
    category: 'blog',
    purposes: ['blog-writer', 'travel-hospitality', 'personal-portfolio'],
    thumbnail: '/templates/magazine-editorial.jpg',
    description: 'Editorial magazine layout with blog-forward content hub',
    defaultSections: ['hero', 'about', 'blog', 'gallery', 'social', 'contact'],
    defaultTheme: base({ primaryColor: '#292524', secondaryColor: '#78716c', backgroundColor: '#fafaf9', textColor: '#1c1917', fontFamily: 'Lora', borderRadius: 'none', animation: 'subtle', spacing: 'relaxed' }),
    defaultLayoutPreset: 'magazine',
    layoutTags: ['Magazine', 'Blog'],
  },
  {
    id: 'magazine-minimal',
    name: 'Writer Minimal',
    category: 'blog',
    purposes: ['blog-writer', 'resume-cv'],
    thumbnail: '/templates/magazine-minimal.jpg',
    description: 'Single-column reading experience for writers and journalists',
    defaultSections: ['hero', 'about', 'blog', 'social', 'contact'],
    defaultTheme: base({ primaryColor: '#44403c', secondaryColor: '#a8a29e', backgroundColor: '#ffffff', textColor: '#1c1917', fontFamily: 'Georgia', borderRadius: 'none', animation: 'none', spacing: 'relaxed' }),
    defaultLayoutPreset: 'single-column',
    layoutTags: ['Single Column', 'Blog'],
  },
  {
    id: 'magazine-lifestyle',
    name: 'Lifestyle Magazine',
    category: 'blog',
    purposes: ['blog-writer', 'travel-hospitality', 'event-wedding'],
    thumbnail: '/templates/magazine-lifestyle.jpg',
    description: 'Featured hero with carousel gallery and editorial sections',
    defaultSections: ['hero', 'about', 'blog', 'gallery', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#be185d', secondaryColor: '#f9a8d4', backgroundColor: '#fff1f2', textColor: '#881337', fontFamily: 'Playfair Display', borderRadius: 'sm', animation: 'subtle' }),
    defaultLayoutPreset: 'featured-hero',
    layoutTags: ['Featured Hero', 'Magazine'],
  },

  // ── Landing Page ──
  {
    id: 'landing-conversion',
    name: 'Conversion Landing',
    category: 'landing',
    purposes: ['saas-startup', 'freelancer-services', 'fitness-coach', 'education-course'],
    thumbnail: '/templates/landing-conversion.jpg',
    description: 'High-converting one-page scroll with pricing and social proof',
    defaultSections: ['hero', 'about', 'services', 'stats', 'pricing', 'testimonials', 'faq', 'contact'],
    defaultTheme: base({ primaryColor: '#4f46e5', secondaryColor: '#818cf8', accentColor: '#f59e0b', backgroundColor: '#030712', textColor: '#f9fafb', fontFamily: 'Inter', borderRadius: 'lg', animation: 'expressive' }),
    defaultLayoutPreset: 'one-page',
    layoutTags: ['One-Page', 'Landing'],
  },
  {
    id: 'landing-saas-pro',
    name: 'SaaS Pro Landing',
    category: 'landing',
    purposes: ['saas-startup', 'online-store'],
    thumbnail: '/templates/landing-saas-pro.jpg',
    description: 'Split hero SaaS landing with feature grid and 3-tier pricing',
    defaultSections: ['hero', 'about', 'services', 'stats', 'pricing', 'faq', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#0d9488', secondaryColor: '#2dd4bf', backgroundColor: '#042f2e', textColor: '#ecfdf5', fontFamily: 'Inter', borderRadius: 'md', animation: 'moderate' }),
    defaultLayoutPreset: 'saas-modern',
    layoutTags: ['SaaS Modern', 'Landing'],
  },
  {
    id: 'landing-product',
    name: 'Product Launch',
    category: 'landing',
    purposes: ['saas-startup', 'online-store', 'agency-studio'],
    thumbnail: '/templates/landing-product.jpg',
    description: 'Banner impact landing with F-shape content flow for product launches',
    defaultSections: ['hero', 'about', 'services', 'stats', 'pricing', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#dc2626', secondaryColor: '#f87171', accentColor: '#fbbf24', backgroundColor: '#18181b', textColor: '#fafafa', fontFamily: 'Poppins', borderRadius: 'lg', animation: 'expressive' }),
    defaultLayoutPreset: 'f-shape',
    layoutTags: ['F-Shape', 'Landing'],
  },
  {
    id: 'landing-agency',
    name: 'Agency Landing',
    category: 'landing',
    purposes: ['agency-studio', 'freelancer-services', 'business-company'],
    thumbnail: '/templates/landing-agency.jpg',
    description: 'Z-shape alternating sections for creative agency pitches',
    defaultSections: ['hero', 'about', 'services', 'projects', 'team', 'testimonials', 'contact'],
    defaultTheme: base({ primaryColor: '#9333ea', secondaryColor: '#c084fc', backgroundColor: '#0f0a1e', textColor: '#faf5ff', fontFamily: 'Montserrat', borderRadius: 'none', animation: 'expressive' }),
    defaultLayoutPreset: 'z-shape',
    layoutTags: ['Z-Shape', 'Landing'],
  },
];
